COLUMNS_TO_REMOVE = [
            "id",
            "conversation_id",
            "created_at",
            "timezone",
            "user_id",
            "username",
            "name",
            "place",
            "language",
            "urls",
            "photos",
            "date",
            "hashtags",
            "cashtags",
            "link",
            "retweet",
            "quote_url",
            "video",
            "thumbnail",
            "near",
            "geo",
            "source",
            "user_rt_id",
            "user_rt",
            "retweet_id",
            "reply_to",
            "retweet_date",
            "translate",
            "trans_src",
            "trans_dest",
        ]

DESCRIPTION_DICTIONARY = {
            "CC": "coordinating conjunction",
            "CD": "cardinal digit",
            "DT": "determiner",
            "EX": "existential there",
            "FW": "foreign word",
            "IN": "preposition/subordinating conjunction",
            "JJ": "This NLTK POS Tag is an adjective (large)",
            "JJR": "adjective, comparative (larger)",
            "JJS": "adjective, superlative",
            "LS": "list market",
            "MD": "modal (could, will)",
            "NN": "noun, singular (cat, tree)",
            "NNS": "noun plural (desks)",
            "NNP": "proper noun, singular (sarah)",
            "NNPS": "proper noun, plural (indians or americans)",
            "PDT": "predeterminer (all, both, half)",
            "POS": "possessive ending (parent\ ‘s)",
            "PRP": "personal pronoun (hers, herself, him,himself)",
            "PRP$": "possessive pronoun (her, his, mine, my, our )",
            "RB": "adverb (occasionally, swiftly)",
            "RBR": "adverb, comparative (greater)",
            "RBS": "adverb, superlative (biggest)",
            "RP": "particle (about)",
            "TO": "infinite marker (to)",
            "UH": "interjection (goodbye)",
            "VB": "verb (ask)",
            "VBG": "verb gerund (judging)",
            "VBD": "verb past tense (pleaded)",
            "VBN": "verb past participle (reunified)",
            "VBP": "verb, present tense not 3rd person singular(wrap)",
            "VBZ": "verb, present tense with 3rd person singular (bases)",
            "WDT": "wh-determiner (that, what)",
            "WP": "wh- pronoun (who)",
            "WRB": "wh- adverb (how)",
        }